package packager

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/goreleaser/nfpm/v2"
	_ "github.com/goreleaser/nfpm/v2/deb"
)

const (
	defaultMaintainer = "php-extension-builder <php-extension-builder@example.invalid>"
)

type DebPackageDetails struct {
	ExtensionName  string
	PackageVersion string
	PhpMajorMinor  string
	Arch           string
	ExtensionDir   string
}

func (d DebPackageDetails) Filename() (string, error) {
	packageName := debPackageName(d.ExtensionName, d.PhpMajorMinor)
	version := d.PackageVersion
	arch, err := debianArchitecture(d.Arch)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("%s_%s_%s.deb", packageName, version, arch), nil
}

func CreateDeb(sourceFile, outputFile string, details DebPackageDetails) error {
	phpApi, err := phpApiFromExtensionDir(details.ExtensionDir)
	if err != nil {
		return err
	}
	debArch, err := debianArchitecture(details.Arch)
	if err != nil {
		return err
	}

	postinstContent := postinstScript(details.ExtensionName, details.PhpMajorMinor)
	prermContent := prermScript(details.ExtensionName, details.PhpMajorMinor)

	tmpPostinst, err := os.CreateTemp("", "postinst-*")
	if err != nil {
		return fmt.Errorf("failed to create temp file for postinst script: %w", err)
	}
	defer os.Remove(tmpPostinst.Name())
	defer tmpPostinst.Close()
	if _, err := tmpPostinst.WriteString(postinstContent); err != nil {
		return err
	}

	tmpPrerm, err := os.CreateTemp("", "prerm-*")
	if err != nil {
		return fmt.Errorf("failed to create temp file for prerm script: %w", err)
	}
	defer os.Remove(tmpPrerm.Name())
	defer tmpPrerm.Close()
	if _, err := tmpPrerm.WriteString(prermContent); err != nil {
		return err
	}

	iniContent := fmt.Sprintf("extension=%s.so\n", details.ExtensionName)
	tmpIni, err := os.CreateTemp("", "ini-*")
	if err != nil {
		return fmt.Errorf("failed to create temp file for ini: %w", err)
	}
	defer os.Remove(tmpIni.Name())
	defer tmpIni.Close()
	if _, err := tmpIni.WriteString(iniContent); err != nil {
		return err
	}

	pkgName := debPackageName(details.ExtensionName, details.PhpMajorMinor)
	virtPkgName := virtualPackageName(details.ExtensionName)

	yamlConfig := fmt.Sprintf(`
name: %[1]q
version: %[2]q
arch: %[3]q
platform: "linux"
section: "php"
priority: "optional"
maintainer: %[4]q
description: |
  PHP %[5]s extension
  Prebuilt PHP extension generated by php-extension-builder.
depends:
  - "phpapi-%[6]s"
  - "php-common"
provides:
  - %[7]q
contents:
  - src: %[8]q
    dst: "/usr/lib/php/%[6]s/%[5]s.so"
    file_info:
      mode: 0644
  - src: %[9]q
    dst: "/etc/php/%[10]s/mods-available/%[5]s.ini"
    file_info:
      mode: 0644
scripts:
  postinstall: %[11]q
  preremove: %[12]q
`,
		pkgName,                // 1
		details.PackageVersion, // 2
		debArch,                // 3
		defaultMaintainer,      // 4
		details.ExtensionName,  // 5
		phpApi,                 // 6
		virtPkgName,            // 7
		sourceFile,             // 8
		tmpIni.Name(),          // 9
		details.PhpMajorMinor,  // 10
		tmpPostinst.Name(),     // 11
		tmpPrerm.Name(),        // 12
	)

	config, err := nfpm.Parse(strings.NewReader(yamlConfig))
	if err != nil {
		return fmt.Errorf("failed to parse nfpm config: %w", err)
	}

	info, err := config.Get("deb")
	if err != nil {
		return fmt.Errorf("failed to get nfpm deb info: %w", err)
	}

	packager, err := nfpm.Get("deb")
	if err != nil {
		return fmt.Errorf("failed to find nfpm packager for deb: %w", err)
	}

	parent := filepath.Dir(outputFile)
	if parent != "" && parent != "." {
		if err := os.MkdirAll(parent, 0755); err != nil {
			return fmt.Errorf("failed to create output directory %s: %w", parent, err)
		}
	}

	out, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create package %s: %w", outputFile, err)
	}
	defer out.Close()

	if err := packager.Package(info, out); err != nil {
		return fmt.Errorf("failed to build deb package: %w", err)
	}

	return nil
}

func debPackageName(extensionName, phpMajorMinor string) string {
	return fmt.Sprintf("php%s-%s", phpMajorMinor, debianPackageComponent(extensionName))
}

func virtualPackageName(extensionName string) string {
	return fmt.Sprintf("php-%s", debianPackageComponent(extensionName))
}

func debianPackageComponent(extensionName string) string {
	return strings.ToLower(strings.ReplaceAll(extensionName, "_", "-"))
}

func postinstScript(extensionName, phpMajorMinor string) string {
	return fmt.Sprintf(
		"#!/bin/sh\n"+
			"set -e\n"+
			"if command -v phpenmod >/dev/null 2>&1; then\n"+
			"\tphpenmod -v %s %s || true\n"+
			"fi\n"+
			"exit 0\n",
		shellQuote(phpMajorMinor),
		shellQuote(extensionName),
	)
}

func prermScript(extensionName, phpMajorMinor string) string {
	return fmt.Sprintf(
		"#!/bin/sh\n"+
			"set -e\n"+
			"case \"$1\" in\n"+
			"\tremove|deconfigure)\n"+
			"\t\tif command -v phpdismod >/dev/null 2>&1; then\n"+
			"\t\t\tphpdismod -v %s %s || true\n"+
			"\t\tfi\n"+
			"\t\t;;\n"+
			"esac\n"+
			"exit 0\n",
		shellQuote(phpMajorMinor),
		shellQuote(extensionName),
	)
}

func phpApiFromExtensionDir(extensionDir string) (string, error) {
	trimmed := strings.TrimRight(extensionDir, "/")
	if trimmed == "" {
		return "", fmt.Errorf("PHP extension directory is empty")
	}

	parts := strings.Split(trimmed, "/")
	basename := parts[len(parts)-1]
	if basename == "" {
		return "", fmt.Errorf("PHP extension directory is empty")
	}

	subparts := strings.Split(basename, "-")
	phpApi := subparts[len(subparts)-1]
	if phpApi == "" {
		return "", fmt.Errorf("could not infer PHP API id from extension directory")
	}

	for _, char := range phpApi {
		if char < '0' || char > '9' {
			return "", fmt.Errorf("could not infer PHP API id from extension directory")
		}
	}

	return phpApi, nil
}

func debianArchitecture(arch string) (string, error) {
	switch arch {
	case "x86_64":
		return "amd64", nil
	case "arm64":
		return "arm64", nil
	case "x86":
		return "i386", nil
	default:
		return "", fmt.Errorf("unsupported Debian architecture: %s", arch)
	}
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
