use anyhow::{Context, Result, bail};
use flate2::Compression;
use flate2::write::GzEncoder;
use std::collections::BTreeSet;
use std::fs::{self, File};
use std::io::{Cursor, Write};
use std::path::{Path, PathBuf};
use tar::{Builder, EntryType, Header};

const DEBIAN_BINARY: &[u8] = b"2.0\n";
const DEFAULT_MAINTAINER: &str = "php-extension-builder <php-extension-builder@example.invalid>";

pub struct DebPackageDetails<'a> {
    pub extension_name: &'a str,
    pub package_version: &'a str,
    pub php_major_minor: &'a str,
    pub arch: &'a str,
    pub extension_dir: &'a str,
}

impl DebPackageDetails<'_> {
    pub fn filename(&self) -> Result<String> {
        let package_name = package_name(self.extension_name, self.php_major_minor);
        let version = package_version(self.package_version);
        let arch = debian_architecture(self.arch)?;

        Ok(format!("{package_name}_{version}_{arch}.deb"))
    }
}

pub fn create_deb(
    source_file: &Path,
    output_file: &Path,
    details: &DebPackageDetails<'_>,
) -> Result<()> {
    let parent = output_file.parent().unwrap_or_else(|| Path::new("."));
    if !parent.as_os_str().is_empty() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create output directory {}", parent.display()))?;
    }

    let source_bytes = fs::read(source_file)
        .with_context(|| format!("failed to read built extension {}", source_file.display()))?;
    let package = build_package(details, &source_bytes)?;

    let mut output = File::create(output_file)
        .with_context(|| format!("failed to create package {}", output_file.display()))?;
    output
        .write_all(&package)
        .with_context(|| format!("failed to write package {}", output_file.display()))?;

    Ok(())
}

fn build_package(details: &DebPackageDetails<'_>, source_bytes: &[u8]) -> Result<Vec<u8>> {
    let php_api = php_api_from_extension_dir(details.extension_dir)?;
    let control = control_file(details, &php_api, source_bytes.len())?;
    let postinst = postinst_script(details.extension_name, details.php_major_minor);
    let prerm = prerm_script(details.extension_name, details.php_major_minor);

    let control_tar = gzip_tar(&[
        TarEntry::new("control", 0o644, control.into_bytes()),
        TarEntry::new("postinst", 0o755, postinst.into_bytes()),
        TarEntry::new("prerm", 0o755, prerm.into_bytes()),
    ])?;

    let data_tar = gzip_tar(&[
        TarEntry::new(
            format!("usr/lib/php/{php_api}/{}.so", details.extension_name),
            0o644,
            source_bytes.to_vec(),
        ),
        TarEntry::new(
            format!(
                "etc/php/{}/mods-available/{}.ini",
                details.php_major_minor, details.extension_name
            ),
            0o644,
            format!("extension={}.so\n", details.extension_name).into_bytes(),
        ),
    ])?;

    let mut package = Vec::new();
    package.extend_from_slice(b"!<arch>\n");
    write_ar_member(&mut package, "debian-binary", DEBIAN_BINARY)?;
    write_ar_member(&mut package, "control.tar.gz", &control_tar)?;
    write_ar_member(&mut package, "data.tar.gz", &data_tar)?;

    Ok(package)
}

fn package_name(extension_name: &str, php_major_minor: &str) -> String {
    format!(
        "php{php_major_minor}-{}",
        debian_package_component(extension_name)
    )
}

fn virtual_package_name(extension_name: &str) -> String {
    format!("php-{}", debian_package_component(extension_name))
}

fn debian_package_component(extension_name: &str) -> String {
    extension_name
        .chars()
        .map(|character| match character {
            '_' => '-',
            other => other.to_ascii_lowercase(),
        })
        .collect()
}

fn package_version(package_version: &str) -> &str {
    package_version
}

fn control_file(
    details: &DebPackageDetails<'_>,
    php_api: &str,
    source_size: usize,
) -> Result<String> {
    let package_name = package_name(details.extension_name, details.php_major_minor);
    let virtual_package_name = virtual_package_name(details.extension_name);
    let version = package_version(details.package_version);
    let arch = debian_architecture(details.arch)?;
    let installed_size = installed_size_kib(source_size);

    Ok(format!(
        "Package: {package_name}\n\
Version: {version}\n\
Section: php\n\
Priority: optional\n\
Architecture: {arch}\n\
Maintainer: {DEFAULT_MAINTAINER}\n\
Depends: phpapi-{php_api}, php-common\n\
Provides: {virtual_package_name}\n\
Installed-Size: {installed_size}\n\
Description: PHP {} extension\n\
\x20Prebuilt PHP extension generated by php-extension-builder.\n",
        details.extension_name
    ))
}

fn postinst_script(extension_name: &str, php_major_minor: &str) -> String {
    format!(
        "#!/bin/sh\n\
         set -e\n\
         if command -v phpenmod >/dev/null 2>&1; then\n\
         \tphpenmod -v {} {} || true\n\
         fi\n\
         exit 0\n",
        shell_quote(php_major_minor),
        shell_quote(extension_name)
    )
}

fn prerm_script(extension_name: &str, php_major_minor: &str) -> String {
    format!(
        "#!/bin/sh\n\
         set -e\n\
         case \"$1\" in\n\
         \tremove|deconfigure)\n\
         \t\tif command -v phpdismod >/dev/null 2>&1; then\n\
         \t\t\tphpdismod -v {} {} || true\n\
         \t\tfi\n\
         \t\t;;\n\
         esac\n\
         exit 0\n",
        shell_quote(php_major_minor),
        shell_quote(extension_name)
    )
}

fn installed_size_kib(source_size: usize) -> usize {
    source_size.div_ceil(1024).max(1)
}

fn gzip_tar(entries: &[TarEntry]) -> Result<Vec<u8>> {
    let encoder = GzEncoder::new(Vec::new(), Compression::default());
    let mut builder = Builder::new(encoder);

    for directory in directories(entries) {
        append_directory(&mut builder, &directory)?;
    }

    for entry in entries {
        append_file(&mut builder, entry)?;
    }

    builder.finish().context("failed to finish tar archive")?;
    let encoder = builder.into_inner().context("failed to finish gzip tar")?;
    encoder.finish().context("failed to finish gzip stream")
}

fn directories(entries: &[TarEntry]) -> BTreeSet<PathBuf> {
    let mut directories = BTreeSet::new();

    for entry in entries {
        let mut current = Path::new(&entry.path).parent();
        while let Some(directory) = current {
            if directory.as_os_str().is_empty() {
                break;
            }

            directories.insert(directory.to_path_buf());
            current = directory.parent();
        }
    }

    directories
}

fn append_directory<W: Write>(builder: &mut Builder<W>, path: &Path) -> Result<()> {
    let mut header = Header::new_gnu();
    header.set_entry_type(EntryType::Directory);
    header.set_size(0);
    header.set_mode(0o755);
    header.set_uid(0);
    header.set_gid(0);
    header.set_mtime(0);
    header.set_cksum();

    builder
        .append_data(&mut header, path, Cursor::new(Vec::new()))
        .with_context(|| format!("failed to add {} to tar archive", path.display()))
}

fn append_file<W: Write>(builder: &mut Builder<W>, entry: &TarEntry) -> Result<()> {
    let mut header = Header::new_gnu();
    header.set_size(
        entry
            .data
            .len()
            .try_into()
            .context("tar entry is too large")?,
    );
    header.set_mode(entry.mode);
    header.set_uid(0);
    header.set_gid(0);
    header.set_mtime(0);
    header.set_cksum();

    builder
        .append_data(&mut header, &entry.path, Cursor::new(entry.data.as_slice()))
        .with_context(|| format!("failed to add {} to tar archive", entry.path))
}

fn write_ar_member(writer: &mut Vec<u8>, name: &str, data: &[u8]) -> Result<()> {
    if name.len() > 15 {
        bail!("ar member name is too long: {name}");
    }

    let identifier = format!("{name}/");
    let header = format!(
        "{identifier:<16}{:<12}{:<6}{:<6}{:<8}{:<10}`\n",
        0,
        0,
        0,
        "100644",
        data.len()
    );

    writer.extend_from_slice(header.as_bytes());
    writer.extend_from_slice(data);
    if !data.len().is_multiple_of(2) {
        writer.push(b'\n');
    }

    Ok(())
}

fn php_api_from_extension_dir(extension_dir: &str) -> Result<String> {
    let basename = extension_dir
        .trim_end_matches('/')
        .rsplit('/')
        .next()
        .filter(|value| !value.is_empty())
        .context("PHP extension directory is empty")?;
    let php_api = basename
        .rsplit('-')
        .next()
        .filter(|value| value.chars().all(|character| character.is_ascii_digit()))
        .context("could not infer PHP API id from extension directory")?;

    Ok(php_api.to_string())
}

fn debian_architecture(arch: &str) -> Result<&'static str> {
    match arch {
        "x86_64" => Ok("amd64"),
        "arm64" => Ok("arm64"),
        "x86" => Ok("i386"),
        other => bail!("unsupported Debian architecture: {other}"),
    }
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

struct TarEntry {
    path: String,
    mode: u32,
    data: Vec<u8>,
}

impl TarEntry {
    fn new(path: impl Into<String>, mode: u32, data: Vec<u8>) -> Self {
        Self {
            path: path.into(),
            mode,
            data,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        DebPackageDetails, build_package, control_file, debian_architecture,
        debian_package_component, php_api_from_extension_dir, postinst_script, prerm_script,
    };
    use anyhow::{Context, Result, bail};
    use flate2::read::GzDecoder;
    use std::collections::BTreeMap;
    use std::io::Read;
    use tar::Archive;

    #[test]
    fn creates_debian_package_filename() {
        let details = details();

        assert_eq!(details.filename().unwrap(), "php8.3-foo_1.2.3_amd64.deb");
    }

    #[test]
    fn normalizes_extension_name_for_debian_package_name() {
        assert_eq!(debian_package_component("Test_Ext"), "test-ext");
    }

    #[test]
    fn maps_debian_architectures() {
        assert_eq!(debian_architecture("x86_64").unwrap(), "amd64");
        assert_eq!(debian_architecture("arm64").unwrap(), "arm64");
        assert_eq!(debian_architecture("x86").unwrap(), "i386");
        assert!(debian_architecture("sparc").is_err());
    }

    #[test]
    fn extracts_php_api_from_extension_dir() {
        assert_eq!(
            php_api_from_extension_dir("/usr/local/lib/php/extensions/no-debug-non-zts-20230831")
                .unwrap(),
            "20230831"
        );
        assert_eq!(
            php_api_from_extension_dir("/usr/lib/php/20230831").unwrap(),
            "20230831"
        );
        assert!(php_api_from_extension_dir("/usr/lib/php/extensions/debug").is_err());
    }

    #[test]
    fn creates_control_file() {
        let control = control_file(&details(), "20230831", 2048).unwrap();

        assert!(control.contains("Package: php8.3-foo\n"));
        assert!(control.contains("Version: 1.2.3\n"));
        assert!(control.contains("Architecture: amd64\n"));
        assert!(control.contains("Depends: phpapi-20230831, php-common\n"));
        assert!(control.contains("Provides: php-foo\n"));
        assert!(control.contains("Description: PHP foo extension\n"));
        assert!(
            control.contains("\n Prebuilt PHP extension generated by php-extension-builder.\n")
        );
    }

    #[test]
    fn creates_maintainer_scripts() {
        assert!(postinst_script("foo", "8.3").contains("phpenmod -v '8.3' 'foo' || true"));
        assert!(prerm_script("foo", "8.3").contains("phpdismod -v '8.3' 'foo' || true"));
    }

    #[test]
    fn creates_deb_archive_members_and_payloads() {
        let package = build_package(&details(), b"fake-so").unwrap();
        let members = ar_members(&package).unwrap();

        assert_eq!(
            members.keys().cloned().collect::<Vec<_>>(),
            vec!["control.tar.gz", "data.tar.gz", "debian-binary"]
        );
        assert_eq!(members["debian-binary"], b"2.0\n");

        let control_files = tar_files(&members["control.tar.gz"]).unwrap();
        assert!(String::from_utf8_lossy(&control_files["control"]).contains("Package: php8.3-foo"));
        assert!(control_files.contains_key("postinst"));
        assert!(control_files.contains_key("prerm"));

        let data_files = tar_files(&members["data.tar.gz"]).unwrap();
        assert_eq!(data_files["usr/lib/php/20230831/foo.so"], b"fake-so");
        assert_eq!(
            data_files["etc/php/8.3/mods-available/foo.ini"],
            b"extension=foo.so\n"
        );
    }

    fn details() -> DebPackageDetails<'static> {
        DebPackageDetails {
            extension_name: "foo",
            package_version: "1.2.3",
            php_major_minor: "8.3",
            arch: "x86_64",
            extension_dir: "/usr/local/lib/php/extensions/no-debug-non-zts-20230831",
        }
    }

    fn ar_members(package: &[u8]) -> Result<BTreeMap<String, Vec<u8>>> {
        if !package.starts_with(b"!<arch>\n") {
            bail!("missing ar header");
        }

        let mut members = BTreeMap::new();
        let mut offset = 8;
        while offset < package.len() {
            let header = package
                .get(offset..offset + 60)
                .context("truncated ar header")?;
            let name = String::from_utf8_lossy(&header[0..16])
                .trim()
                .trim_end_matches('/')
                .to_string();
            let size: usize = String::from_utf8_lossy(&header[48..58]).trim().parse()?;
            offset += 60;

            let end = offset + size;
            let data = package.get(offset..end).context("truncated ar member")?;
            members.insert(name, data.to_vec());
            offset = end + (size % 2);
        }

        Ok(members)
    }

    fn tar_files(gzip_tar: &[u8]) -> Result<BTreeMap<String, Vec<u8>>> {
        let decoder = GzDecoder::new(gzip_tar);
        let mut archive = Archive::new(decoder);
        let mut files = BTreeMap::new();

        for entry in archive.entries()? {
            let mut entry = entry?;
            if !entry.header().entry_type().is_file() {
                continue;
            }

            let path = entry.path()?.to_string_lossy().to_string();
            let mut contents = Vec::new();
            entry.read_to_end(&mut contents)?;
            files.insert(path, contents);
        }

        Ok(files)
    }
}
